export const shittyStars = [
    {
      id: 1,
      name: "Johnny Depp",
      bio: "Le jet ski c'est mon dada",
      img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQRhB0vwCnr8g35RbqxdbZoMjSQXbC_CQFP6KwdZ6C1qbAU0D7_",
      publishedAt: "2020-10-10",
      isPickedByTeam: true,
    },
    {
      id: 2,
      name: "Johnny Hallyday",
      bio: "hahahahahcedfplêd",
      img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQxjj0RoSJW7ffH0b44uX5yM6NPIRgQuSSVHN5jg68SmGw98N9R",
      publishedAt: "2021-10-10",
      isPickedByTeam: true,
    },
    {
        id: 3,
        name: "Justin Bieber",
        bio: "hahahahahcedfplêd",
        img: "https://media.gqmagazine.fr/photos/640b1aa5bd6f5c8e911df9ea/master/pass/010322_JBHair_01.jpg",
        publishedAt: "2021-10-10",
        isPickedByTeam: true,
    },
    {
      id: 4,
      name: "Angelina Jolie",
      bio: "hahahahahcedfplêd",
      img: "https://upload.wikimedia.org/wikipedia/commons/3/34/Angelina_Jolie_%2848462859552%29_%28cropped%29.jpg",
      publishedAt: "2021-10-13",
      isPickedByTeam: false,
    },
    {
      id: 5,
      name: "Vincent Lagaffe",
      bio: "Le jet ski c'est mon dada",
      img: "https://file1.telestar.fr/var/telestar/storage/images/2015/photos/vincent-lagaf-decroche-un-record-du-monde-grace-au-flyboard-!-photos-132229/989014-1-fre-FR/Vincent-Lagaf-decroche-un-record-du-monde-grace-au-Flyboard-!-Photos.jpg?alias=original",
      publishedAt: "2020-12-10",
      isPickedByTeam: true,
    },
  ];